# adapted from https://github.com/piensa/geonode/blob/pubsub/docker-compose.override.yml

version: '2'

services:
  django:
    # Loading the app is defined here to allow for 
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True

  celery:
    # Loading the app is defined here to allow for 
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True

  #consumers:
  #  build: .
  #  # Loading the app is defined here to allow for
  #  # autoreload on changes it is mounted on top of the
  #  # old copy that docker added when creating the image
  #  volumes:
  #    - '.:/usr/src/app'
  #  environment:
  #    - DEBUG=True